"""Project frozen raw metrics to compact, auditable publication evidence."""
import argparse
import copy
import hashlib
import json
from pathlib import Path


def sha(path): return hashlib.sha256(path.read_bytes()).hexdigest()


def main(source, target):
    source, target = Path(source), Path(target)
    target.mkdir(parents=True, exist_ok=True)
    result = json.loads((source/'evaluation.json').read_text())
    games = json.loads((source/'per_game.json').read_text())
    # Overall calibration bins stay intact. Every subgroup and game's actual
    # scalar loss, denominator and infinite count is preserved; only repeated
    # bins are omitted from this publication projection, never from raw output.
    def compact(metrics):
        for values in metrics.values():
            for domain in values.values():
                domain.pop('bins', None)
                if 'calibration' in domain:
                    domain['calibration'].pop('bins', None)
    for group in result['groups']:
        if group['dimension'] != 'all': compact(group['metrics'])
    for game in games: compact(game['metrics'])
    result['publication_projection'] = dict(source_sha256=sha(source/'evaluation.json'),
        omitted='Repeated subgroup calibration bins only; original overall bins and all subgroup scalar metrics retained',
        script_sha256=sha(Path(__file__)))
    for name, value in [('evaluation.json', result), ('per_game.json', games)]:
        (target/name).write_text(json.dumps(value, ensure_ascii=False, indent=2, allow_nan=False)+'\n')
    for name in ('preregister.json', 'verification.json', 'baseline_verification.json'):
        (target/name).write_bytes((source/name).read_bytes())
    projection = dict(raw_sha256={name:sha(source/name) for name in ('evaluation.json','per_game.json')},
        published_sha256={name:sha(target/name) for name in ('evaluation.json','per_game.json')},
        script_sha256=sha(Path(__file__)), note='No loss or decision recomputed; calibration-bin projection only. Full raw files regenerated by registered experiment.')
    (target/'projection.json').write_text(json.dumps(projection, indent=2)+'\n')


if __name__ == '__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--input',required=True);parser.add_argument('--output',required=True)
    args=parser.parse_args();main(args.input,args.output)
